## Leader Key
unbind C-b
unbind C-t
set -g prefix C-t
## Pressing C-t twice sends C-t to the program in the pane
bind C-t send-prefix

set -g mouse on

set -g base-index 1
# set -g renumber-windows

## Transparent statusbar
set-option -g status-style bg=default
set -g status-fg blue
# set-option -g status-position top

## Bindings for splitting and resizing panes
bind-key -T prefix v split-window -h
bind-key -T prefix - split-window
# -r flag for repeated use without pressing prefix
bind-key -rT prefix h resize-pane -L 3
bind-key -rT prefix j resize-pane -D 3
bind-key -rT prefix k resize-pane -U 3
bind-key -rT prefix l resize-pane -R 3

## Make n repeatable
unbind-key -T prefix n
bind-key -rT prefix n next-window

## prefix \' = C-g (in the root table, ie -n)
bind-key -n C-g command-prompt -T window-target -p index { select-window -t ":%%" }

## Better swap-pane
bind-key -T prefix 'C-m' swap-pane \; select-pane -M

## Smart pane switching with awareness of Vim splits.
## See: https://github.com/christoomey/vim-tmux-navigator
vim_pattern='(\S+/)?g?\.?(view|l?n?vim?x?|fzf)(diff)?(-wrapped)?'
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +${vim_pattern}$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

## Plugins
# set -g @plugin "tmux-plugins/tpm"
# set -g @plugin "christoomey/vim-tmux-navigator"
# anche tmuxifier può essere gestito come plugin
# leader-shift-i to install plugins

# run "~/.tmux/plugins/tpm/tpm"

