# Get editor completions based on the config schema
# "$schema" = "https://starship.rs/config-schema.json"

# Avoid blank line between shell prompts
add_newline = false

[line_break]
disabled = true

[directory]
read_only = " 󰌾"

[git_branch]
symbol = " "

[cpp]
symbol = " "

[lua]
symbol = " "

[python]
symbol = " "

